### ISSUE TITLE
Creating difficulty level for each question

### ISSUE THREAD

**Issue by martianescape** [vinnybod/cse591QA#2]
I created the QAROR environment in my laptop.
Things to do
- [ ] Read the code. Find out what all I need to learn. - 12th 13th 14th
- [ ] Understand where all I need to make the changes. - 12th 13th 14th
- [ ] Learn everything required for the task - 15th 16th 17th
- [ ] Implement changes 18th 19th 20th

**Comment by martianescape** [comment]
@archjain: If everything goes according to my plan. You will have 5 days to do the front end if necessary.

**Comment by vinnybod** [comment]
Please close this issue if it is complete
