### ISSUE TITLE
message not retaining the line spacing

### ISSUE THREAD

**Issue by archjain** [vinnybod/cse591QA#4]
@vinnybod ..look at the screenshots, I think it will be handled through ruby.
Also let me know any improvements in display you want..I will be doing some more though

<img width="726" alt="compose" src="https://cloud.githubusercontent.com/assets/14120959/13310057/0a17cbce-db40-11e5-8790-0896f73e4f46.PNG">
<img width="757" alt="msgbody" src="https://cloud.githubusercontent.com/assets/14120959/13310058/0a2ee78c-db40-11e5-888b-2692814e7667.PNG">

**Comment by vinnybod** [comment]
I will look into this.

**Comment by vinnybod** [comment]
When displaying the body of the message try wrapping it with simple_format

examples here:
http://apidock.com/rails/v3.2.3/ActionView/Helpers/TextHelper/simple_format

**Comment by archjain** [comment]
Resolved !!
![image](https://cloud.githubusercontent.com/assets/14120959/13327998/93043ab2-dba9-11e5-972d-1c6e561c27be.png)

**Comment by archjain** [comment]
Closing the issue

**Comment by vinnybod** [comment]
WOOHOO! that UI looks great by the way :)
