### ISSUE TITLE
I need sender's name instead of id. How to retrieve it ?

### ISSUE THREAD

**Issue by archjain** [vinnybod/cse591QA#6]
@vinnybod 

![image](https://cloud.githubusercontent.com/assets/14120959/13331222/c20e1bd8-dbb9-11e5-80b1-e2a5d68a5043.png)

**Comment by vinnybod** [comment]
in the loop that builds the list of emails, use the find function to find the user by the id of the sender attached the the message object.

Try something like this
 <% for m in @messages %>
<% sentFrom = User.find(m.sent_messageable_id) %>
<%= m.sentFrom %>
....

**Comment by archjain** [comment]
Working fine
![image](https://cloud.githubusercontent.com/assets/14120959/13336014/15131b28-dbd1-11e5-8af1-8ec70ac33548.png)
