### ISSUE TITLE
opened field

### ISSUE THREAD

**Issue by archjain** [vinnybod/cse591QA#7]
As I understand opened field is for if the message is read or not before?
If that is so, the image below shows false for all the messages.... @vinnybod 
![image](https://cloud.githubusercontent.com/assets/14120959/13336033/2b4ee282-dbd1-11e5-8c63-b27461e5c5ce.png)

**Comment by vinnybod** [comment]
If we want to track messages that have been read, that field can be used as a conditional, like 
If read = false
   message will be blue
else message will be white

**Comment by archjain** [comment]
so us there any such kind of field? I thought opened is the one

**Comment by vinnybod** [comment]
to use this field we will just need to make a few changes to the controller. No big deal. Do you want me to add it? So that when they view the message it is marked as read?

**Comment by archjain** [comment]
If it doesn't take much time. Otherwise we can include it in next delivery

**Comment by vinnybod** [comment]
I'm running into the "mass assignment" error again with this one. Let's just try to add it in if we have extra time. By the way I have added the ability to message directly from a user's profile. I need to run some tests first, but then i will merge into master

**Comment by archjain** [comment]
Ok, I will try to reply feature
