### ISSUE TITLE
Not able to send through reply

### ISSUE THREAD

**Issue by archjain** [vinnybod/cse591QA#9]
Look at the screenshots below and please let me know whats the error. I am struggling with ruby errors.
I have also attached the code
<img width="721" alt="1" src="https://cloud.githubusercontent.com/assets/14120959/13338137/ace85d22-dbdc-11e5-89ef-13b8b75e46b9.PNG">

After clicking reply

<img width="674" alt="2" src="https://cloud.githubusercontent.com/assets/14120959/13338135/ace64af0-dbdc-11e5-902e-f202b139b0a5.PNG">

Error
<img width="520" alt="4" src="https://cloud.githubusercontent.com/assets/14120959/13338134/ace5f500-dbdc-11e5-936b-86bb93898bcf.PNG">

code
<img width="596" alt="code" src="https://cloud.githubusercontent.com/assets/14120959/13338136/ace6a540-dbdc-11e5-8e82-32004e18770b.PNG">

**Comment by vinnybod** [comment]
@architjain I'm not sure what the issue is there. Going on a whim, just try to make form_for @message into form_for @reply

**Comment by archjain** [comment]
but "reply" is just a div id here

**Comment by vinnybod** [comment]
i get that. I think having the problem is that there is already an instance variable called @message and you are attempting to override it. So for the form_for in reply, just change it to anything but @message
